services:
  bitcoin:
    image: bitcoin/bitcoin:28.1
    command:
      - -regtest=1
      - -server=1
      - -printtoconsole=1
      - -rpcbind=0.0.0.0
      - -rpcallowip=0.0.0.0/0
      - -rpcuser=student
      - -rpcpassword=studentpass
      - -fallbackfee=0.00001
    ports:
      - "18443:18443"
    volumes:
      - bitcoin-regtest:/home/bitcoin/.bitcoin

volumes:
  bitcoin-regtest:
